# Generated by Django 2.0.13 on 2019-08-26 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likers',
            field=models.ManyToManyField(related_name='comment_likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
