# Generated by Django 2.0.13 on 2019-08-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_comment_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_media',
            field=models.BooleanField(default=False),
        ),
    ]
