# Generated by Django 2.0.13 on 2019-08-29 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import messenger.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_auto_20190829_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_authors', to=settings.AUTH_USER_MODEL, verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(related_name='article_comments', to='messenger.Comment', verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='article',
            name='contains',
            field=models.TextField(max_length=5000, verbose_name='contains'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of creation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likers',
            field=models.ManyToManyField(related_name='article_likers', to=settings.AUTH_USER_MODEL, verbose_name='likers'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, upload_to=messenger.models.utils.user_directory_path, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_article', to='messenger.Article', verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_authors', to=settings.AUTH_USER_MODEL, verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contains',
            field=models.TextField(max_length=5000, verbose_name='contains'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of creation'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likers',
            field=models.ManyToManyField(related_name='comment_likers', to=settings.AUTH_USER_MODEL, verbose_name='likers'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, upload_to=messenger.models.utils.user_directory_path, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_last_message',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of last message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='own',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_owns', to=settings.AUTH_USER_MODEL, verbose_name='owns'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_users', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of creation'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='is_valided',
            field=models.BooleanField(default=False, verbose_name='is valided?'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='message',
            field=models.CharField(default='Hello, I would be your friend', max_length=100, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_receivers', to=settings.AUTH_USER_MODEL, verbose_name='receivers'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_senders', to=settings.AUTH_USER_MODEL, verbose_name='senders'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contains',
            field=models.TextField(max_length=5000, verbose_name='contains'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of creation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_received',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of reception'),
        ),
        migrations.AlterField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, upload_to=messenger.models.utils.user_directory_path, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='message',
            name='received',
            field=models.BooleanField(default=False, verbose_name='is received?'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receivers', to=settings.AUTH_USER_MODEL, verbose_name='receivers'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_senders', to=settings.AUTH_USER_MODEL, verbose_name='senders'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of creation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=100, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='received',
            field=models.BooleanField(default=False, verbose_name='received?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='notification_receivers', to=settings.AUTH_USER_MODEL, verbose_name='receivers'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(related_name='user_contacts', to='messenger.Contact', verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of creation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of update'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='no_media',
            field=models.BooleanField(default=False, verbose_name='no media'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='no_image.png', upload_to=messenger.models.utils.user_directory_path, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='username'),
        ),
    ]
