# Generated by Django 2.0.13 on 2019-08-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_auto_20190829_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='received',
            field=models.BooleanField(default=False, verbose_name='is received?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='no_media',
            field=models.BooleanField(default=False, verbose_name='no media?'),
        ),
    ]
