# Generated by Django 2.0.13 on 2019-08-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_auto_20190829_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Francais')], default='en', max_length=2, verbose_name='language'),
        ),
    ]
