# Generated by Django 2.0.13 on 2019-08-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_user_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='message',
        ),
    ]
